services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./backend:/app:cached
      - vendor-volume:/app/vendor
      - framework-volume:/app/storage/framework
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_local
      DB_USERNAME: root
      DB_PASSWORD: secret

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./backend:/app:cached

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel_local
      ALLOW_EMPTY_PASSWORD: yes
      MYSQL_USER: phper
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 4040:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=secret

volumes:
  mysql-volume:
  vendor-volume:
  framework-volume:
